- name: create appengine folder for backward compatibility
  file:
    state: directory
    dest: "{{ gcloud_home }}/appengine"
  become: True
  become_user: "{{ gcloud_user }}"

- name: backward compatibility links for all appengines
  file:
    state: link
    src: "{{ gcloud_home }}/google-cloud-sdk/platform/google_appengine/"
    dest: "{{ item }}"
  become: True
  become_user: "{{ gcloud_user }}"
  with_items:
    - "{{ gcloud_home }}/appengine/python_appengine"
    - "{{ gcloud_home }}/appengine/google_appengine"
    - "{{ gcloud_home }}/appengine/go_appengine"

- name: make appcfg.py/goapp executable again to ensure backward compatibility
  file:
    state: file
    dest: "{{ gcloud_home }}/{{ item }}"
    mode: 0755
  become: True
  become_user: "{{ gcloud_user }}"
  with_items:
    - "google-cloud-sdk/platform/google_appengine/appcfg.py"
    - "google-cloud-sdk/platform/google_appengine/goapp"

- name: download java appengine
  get_url:
    url: "https://storage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-{{ gae_java_version }}.zip"
    dest: /tmp/java_appengine.zip
  become: True
  become_user: "{{ gcloud_user }}"

- name: unpack java appengine
  unarchive:
    remote_src: True
    src: "/tmp/java_appengine.zip"
    dest: "{{ gcloud_home }}/appengine"
    creates: "{{ gcloud_home }}/appengine/appengine-java-sdk-{{ gae_java_version }}"
  become: True
  become_user: "{{ gcloud_user }}"

- name: link java appengine
  file:
    state: link
    src: "{{ gcloud_home }}/appengine/appengine-java-sdk-{{ gae_java_version }}"
    dest: "{{ gcloud_home }}/appengine/java_appengine"
  become: True
  become_user: "{{ gcloud_user }}"

- name: write appengine configuration
  blockinfile:
    dest: "{{ gcloud_home }}/.appcfg_nat"
    create: True
    block: |
      opt_in: false
      timestamp: 0.0
  become: True
  become_user: "{{ gcloud_user }}"
