#!/bin/bash

set -e

# Writing environment variable to Keyfile so it can be loaded later on
echo $GOOGLE_AUTH_JSON > /keyconfig.json
gcloud auth activate-service-account $GOOGLE_AUTH_EMAIL --key-file /keyconfig.json --project $GOOGLE_PROJECT_ID
